version: 3.8
services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - mysql_vol:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    container_name: backend-container
    build: ./bookjuk_backend
    environment:
      - WAIT_HOSTS=db:3306
      - SPRING_DATABASE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATABASE_USERNAME=${MYSQL_USER}
      - SPRING_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - IMGBB_APP_KEY=${IMGBB_APP_KEY}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - PORTONE_SECRET_API=${PORTONE_SECRET_API}
      - PORTONE_SECRET_WEBHOOK=${PORTONE_SECRET_WEBHOOK}
    depends_on:
      - db
    ports:
      - 8080:8080
  frontend:
    container_name: frontend-container
    build: ./bookjuk_frontend
    environment:
      - WAIT_HOSTS=backend:8080
      - REACT_APP_PORT_ONE_STOREID=${REACT_APP_PORT_ONE_STOREID}
      - REACT_APP_PORT_ONE_KACAO_CHANNELKEY=${REACT_APP_PORT_ONE_KACAO_CHANNELKEY}
      - REACT_APP_PORT_ONE_KG_CHANNELKEY=${REACT_APP_PORT_ONE_KG_CHANNELKEY}
      - REACT_APP_KAKAO_CLIENT_ID=${REACT_APP_KAKAO_CLIENT_ID}
      - REACT_APP_KAKAO_REDIRECT_URI=${REACT_APP_KAKAO_REDIRECT_URI}
      - REACT_APP_NAVER_CLIENT_ID=${REACT_APP_NAVER_CLIENT_ID}
      - REACT_APP_NAVER_CALLBACK_URI=${REACT_APP_NAVER_CALLBACK_URI}
    depends_on:
      - backend
    ports:
      - 80:80
volumes:
  mysql_vol: